version: "3.0"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
  app:
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: product-storage-app/build/libs/product-storage-app-1.0.0.jar
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - db